# Use custom format:
format="$username$directory$git_branch$character"

# Prompt symbols 
[username]
format = "[]($style)[(bg:#89b4fa fg:#49628a)$path](bg:#F5C2E7 fg:#49628a)[ ]($style)"

[character]
success_symbol = "[](#a6e3a1 bold)"
error_symbol = "[](#f38ba8)"
vicmd_symbol = "[](#f9e2af)"

[directory]
format = "[]($style)[(bg:#89b4fa fg:#49628a)$path](bg:#F5C2E7 fg:#49628a)[ ]($style)"
style = "bg:#1a1b26 fg:#F5C2E7"

[git_branch]
format = "[]($style)[[ ](bg:#89b4fa fg:#49628a bold)$branch](bg:#89b4fa fg:#4c4f69)[ ]($style)"
style = "bg:#1a1b26 fg:#89b4fa"

